# Generated by Django 5.1.2 on 2024-11-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='twoFactorAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('photo', models.ImageField(upload_to='media/images', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_authentication', models.BooleanField(default=False, verbose_name='Авторизация')),
                ('email', models.EmailField(default='test@test.test', max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Двухфакторная аутентификация',
                'verbose_name_plural': 'Двухфакторная аутентификация',
                'ordering': ['-time_create', 'login'],
            },
        ),
    ]
